server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: order
  datasource:
    name: new_schema1
    url: jdbc:mysql://localhost:3306/new_schema1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.southwind.entity